# Generated by Django 5.0.14 on 2026-10-08 02:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('categoria', models.CharField(choices=[('torta', 'Torta'), ('pastel', 'Pastel'), ('galleta', 'Galleta'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('precio', models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('stock', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
